### PR TITLE
Updated nest dependancies to v6

### PR DESCRIPTION
**Pull request by bashleigh**

### CODE REVIEW

**Comment by probil** [comment]
```js
  "peerDependencies": {
    "@nestjs/common": "^5.1.0"
  },
```
Peer dependencies probably need to be updated

**Comment by bashleigh** [comment]
@probil oooo I missed that. Would you like to create a PR? Not sure what version the peer should be? I was trying to avoid the opposite for anyone <6.0.0. `^5.1.0|^6.0.0`?

**Comment by probil** [comment]
@bashleigh Yeah I would like to create PR. Give me few minutes :)

**Comment by probil** [comment]
@bashleigh Done #88

**Pull request merged**
